title: Emmanuel Adara #your name (or website title) here
logo: "/Images/profile.png?raw=true"  # your photo (or logo) here
#logo: /Images/headshot_circle.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Turning data into stories and algorithms into real-world solutions through machine learning and deep learning.
  <br>
show_downloads: true
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
