title: Emmanuel Adara #your name (or website title) here
#logo: "/images/profile.png?raw=true"  # your photo (or logo) here
logo: /Images/headshot_circle.png
description: > # your text below (remove <br> elements if you don't need line breaks)
show_downloads: true
theme: jekyll-theme-minimal
