title: Emmanuel Adara #your name (or website title) here
logo: "/Images/profile.png?raw=true"  # your photo (or logo) here
#logo: /Images/headshot_circle.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data science enthusiast passionate about applying machine learning and deep learning to solve real-world problems. I thrive on transforming complex data into actionable insights and developing intelligent, scalable models that drive meaningful impact.
  <br><br>
  Ranked in top 10% of undergraduate cohort at Cambridge University.
  <br><br>
show_downloads: true
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
